In [17]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns;sns.set()
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
import string
from sklearn.model_selection import train_test_split

In [18]:
data=pd.read_csv("/Users/akshatjain/Desktop/dataset.csv")
print(data.head())

                  Command Category
0   set an alarm for 2 pm  general
1   set an alarm for 2 am  general
2  set an alarm for 11 pm  general
3   set an alarm for 5 pm  general
4   set an alarm for 4 pm  general


In [19]:
data.shape

(4499, 2)

In [20]:
data['Category'].value_counts()

general        2486
private        1060
non private     953
Name: Category, dtype: int64

In [21]:
def text_cleaning(a):
    remove_punctuation=[char for char in a if char not in string.punctuation]
    #print(remove_punctuation)
    remove_punctuation=''.join(remove_punctuation)
    #print(remove_punctuation)
    return [word for word in remove_punctuation.split() if word.lower() not in stopwords.words('english')]

In [22]:
print(data['Command'].apply(text_cleaning))

0                [set, alarm, 2, pm]
1                    [set, alarm, 2]
2               [set, alarm, 11, pm]
3                [set, alarm, 5, pm]
4                [set, alarm, 4, pm]
                    ...             
4494    [stop, playing, 56, minutes]
4495    [stop, playing, 21, minutes]
4496    [stop, playing, 57, minutes]
4497    [stop, playing, 36, minutes]
4498     [stop, playing, 7, minutes]
Name: Command, Length: 4499, dtype: object


In [23]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer(analyzer=text_cleaning).fit(data['Command'])

bow.vocabulary_

{'set': 1665,
 'alarm': 329,
 '2': 74,
 'pm': 1456,
 '11': 19,
 '5': 175,
 '4': 144,
 '10': 6,
 '6': 199,
 '9': 274,
 '8': 249,
 '1': 5,
 'every': 845,
 'tuesday': 1886,
 'monday': 1287,
 'thursday': 1847,
 'saturday': 1625,
 'friday': 919,
 'sunday': 1791,
 '58': 197,
 'minutes': 1273,
 '24': 102,
 '26': 110,
 '33': 125,
 '59': 198,
 '54': 187,
 '14': 44,
 '57': 195,
 '53': 185,
 'wake': 1944,
 'day': 704,
 '12': 24,
 '7': 221,
 '3': 119,
 'exercise': 849,
 'dinner': 751,
 'mom': 1285,
 'book': 467,
 'reservation': 1563,
 'go': 950,
 'grocery': 980,
 'shopping': 1678,
 'call': 505,
 'assistant': 381,
 'turn': 1887,
 'motor': 1299,
 'walk': 1945,
 'oven': 1385,
 'next': 1346,
 'snooze': 1719,
 'cancel': 525,
 'timer': 1852,
 'much': 1307,
 'time': 1851,
 'left': 1148,
 'washington': 1956,
 'dc': 706,
 'mumbai': 1315,
 'delhi': 723,
 'new': 1344,
 'york': 2009,
 'bangkok': 412,
 'paris': 1405,
 'london': 1190,
 'rome': 1592,
 'chandigarh': 564,
 'barcelona': 417,
 'look': 1193,
 'like':

In [24]:
command_bow=bow.transform(data['Command'])
print(command_bow)

  (0, 74)	1
  (0, 329)	1
  (0, 1456)	1
  (0, 1665)	1
  (1, 74)	1
  (1, 329)	1
  (1, 1665)	1
  (2, 19)	1
  (2, 329)	1
  (2, 1456)	1
  (2, 1665)	1
  (3, 175)	1
  (3, 329)	1
  (3, 1456)	1
  (3, 1665)	1
  (4, 144)	1
  (4, 329)	1
  (4, 1456)	1
  (4, 1665)	1
  (5, 6)	1
  (5, 329)	1
  (5, 1665)	1
  (6, 199)	1
  (6, 329)	1
  (6, 1665)	1
  :	:
  (4492, 1772)	1
  (4493, 171)	1
  (4493, 1273)	1
  (4493, 1449)	1
  (4493, 1772)	1
  (4494, 190)	1
  (4494, 1273)	1
  (4494, 1449)	1
  (4494, 1772)	1
  (4495, 88)	1
  (4495, 1273)	1
  (4495, 1449)	1
  (4495, 1772)	1
  (4496, 195)	1
  (4496, 1273)	1
  (4496, 1449)	1
  (4496, 1772)	1
  (4497, 138)	1
  (4497, 1273)	1
  (4497, 1449)	1
  (4497, 1772)	1
  (4498, 221)	1
  (4498, 1273)	1
  (4498, 1449)	1
  (4498, 1772)	1


In [25]:
x=command_bow.toarray()
print(x)
x.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(4499, 2016)

In [26]:
from sklearn.feature_extraction.text import TfidfTransformer

tfidf=TfidfTransformer().fit(command_bow)
print(tfidf)

command_tfidf=tfidf.transform(command_bow)
print(command_tfidf)

TfidfTransformer()
  (0, 1665)	0.4272329383467707
  (0, 1456)	0.5105177597370041
  (0, 329)	0.5150776342650591
  (0, 74)	0.539943204480439
  (1, 1665)	0.4968592055957079
  (1, 329)	0.5990199753122295
  (1, 74)	0.6279378942154533
  (2, 1665)	0.4086129251510523
  (2, 1456)	0.48826795975731235
  (2, 329)	0.49262910212718747
  (2, 19)	0.5932507434561656
  (3, 1665)	0.41920474832124976
  (3, 1456)	0.5009245537392838
  (3, 329)	0.5053987430686615
  (3, 175)	0.5638387011820263
  (4, 1665)	0.41389388672150745
  (4, 1456)	0.4945783923766665
  (4, 329)	0.4989958986641786
  (4, 144)	0.5788671328076979
  (5, 1665)	0.48719250821328575
  (5, 329)	0.5873656781548955
  (5, 6)	0.6462546093193358
  (6, 1665)	0.459569645482923
  (6, 329)	0.5540631925323207
  (6, 199)	0.6941251469523295
  :	:
  (4492, 5)	0.6280266077609917
  (4493, 1772)	0.4349933237936527
  (4493, 1449)	0.43054332453449284
  (4493, 1273)	0.40322020876239933
  (4493, 171)	0.6803136902924589
  (4494, 1772)	0.4406155342642477
  (4494, 1449)

In [27]:
from sklearn.model_selection import train_test_split

y=data['Category']
X=command_tfidf

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)



In [28]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB().fit(X_train,y_train )
y_predict=model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


print(accuracy_score(y_test, y_predict))
confusion_matrix(y_test, y_predict)

0.9097643097643098


array([[759,  33,  15],
       [ 31, 277,   7],
       [ 38,  10, 315]])